import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CoffeeDeliveryLogo from "./components/Logo/Logo";
import { City } from "./components/City/City";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center px-40">
          <CoffeeDeliveryLogo />
          <City />
        </header>
        {children}
      </body>
    </html>
  );
}
